### PR TITLE
reformats the response stuff as an array so errors array is properly …

### PR DESCRIPTION
**Pull request by tamw-wnet**
@augustuswm @acrosman I added a helper function to make for more useful error logging.  Right now, if something fails, the errors array includes the raw cURL response, which has newlines, and also half the time has an additional json object at the end of it.  This would make sure that the 'response' section of the error return is an actual array.

### CODE REVIEW

**Comment by acrosman** [comment]
I was dealing with an error condition the other day that was annoying because of the inconsistency, so I like the idea.  I'll have to fold this back in with our other work tomorrow to see how well it blends with what I did the other day.  I may want to recommend better handling on zero-hit searches in addition to this improvement to actual errors.

@jesseves is likely to open a couple pull requests in the next couple days as well.

**Comment by tamw-wnet** [comment]
@acrosman let me know how your review turns out.  Another reason I was doing this was because the API-generated error messaging (like 'episode x already has a full_length video asset' etc) are returned in the response mixed in with the full headers that I have to pull the headers half the time to get redirect URIs on success.

**Comment by augustuswm** [comment]
I very much like the idea of cleaning up result/error handling. We do some hacky output of the errors  currently in our use of the client. Couple notes:
1. Does it make sense to unify the two error structures? (ie. returning both info and errors). I think it would make it structurally the same as the update and delete methods as well.
`array('errors' => array('info' => $info, 'response' => $result))`
`array('errors' => array('errors' => $errors, 'result' => $result))`
2. Should 500 failures be handled differently? I think the error I get from PBS looks something like `<h1>500 Error</h1>`. I think this would parse to `Array (
  [status] => '<h1>500 Error</h1>'
)`.

**Comment by tamw-wnet** [comment]
Some of the cosmetic stuff just made merge conflicts, so I'll fix them in this branch and push for further review.  I think that will clean up the issue @augustuswm pointed out about unifiying our error structures.

**Pull request merged**
