### PR TITLE
Helper functions for improved image handling

### LINKED ISSUE #21: Helper function to extract images and generate different sizes
Both WETA and SCETV need to be able to pull images from shows and episodes and ideally resize them using the PBS image handling service. For example see Latest Episodes section of: https://www.scetv.org/program/reel-south

It seems likely that others may find it useful to be able to do similar things so I figured before we generalize what I have for SCETV into the Drupal module we should check to see if it makes sense to add it to the main client library instead.

Basically I'm proposing adding a helper function that would take an asset with a image, and return a specific image profile. The current functions I use are in the form:
`extract_image($data, $image_type, $width, $height)` where `$image_type` are image profiles like `Mezzanine`
and 
`image_path($baseURL, $width, $height, $type = '')`  where `$type` is the image type itself like `jpg`.

### PR DESCRIPTION
**Pull request by acrosman**
When I went to start this I noticed there was already a base function that does some of this work, but not quite what I was looking for.  So this PR does three things:

1. Adds an optional parameter to the existing `get_images()` to return only one image instead of an array.
2. Adds a new static function `extract_images()` that works on arrays returned by previous requests to extract a specific image reference. This avoids having to make a second call back to the API and having to recreate the logic for the extraction outside the library.
3. Adds a second static function `alter_pbs_image()` to handling updates to PBS image references to use HTTPS, and add crop, resize, and format conversion parameters.

Fixes #21

### CODE REVIEW

**Comment by acrosman** [comment]
The rest of those messy merges are repo clean up. Sorry I should have rebased to sort those out.

**Comment by tamw-wnet** [comment]
@acrosman just because I know it'll cause issues for code cleanup, can you change in line 592 (the comment that lists the params)
string $image_prifile
to 
string $image_profile

**Comment by acrosman** [comment]
Oops, thanks for catching that.  Updated.

**Comment by tamw-wnet** [comment]
Just noting that I have been frantic and unable to review this pr.  It will probably be next week.

**Review by tamw-wnet — APPROVED** [review]
This looks like a useful addition.

**Comment by tamw-wnet** [comment]
@acrosman do you mind updating the README with documentation for the new functions?

**Comment by acrosman** [comment]
Not at all.  I'll try to get to it soon.

**Pull request merged**
